language: elixir
matrix:
  include:
    - elixir: "1.5.3"
      otp_release: "20.0"
      env: "EX_RIAK_SKIP_MIX_FORMAT=yes"
    - elixir: "1.6.6"
      otp_release: "20.3.8.2"
dist: trusty
sudo: required

cache:
  directories:
    - _build
    - deps

before_install:
  - curl -s https://packagecloud.io/install/repositories/basho/riak/script.deb.sh | sudo bash
  - sudo apt-get install riak=2.2.3-1
  # Update the riak.conf with the multi backend.
  # See: https://unix.stackexchange.com/a/26289/11325
  - sudo perl -0777 -i.original -pe 's/storage_backend = bitcask/storage_backend = multi\n\nmulti_backend.ex_riak_leveldb.storage_backend = leveldb\nmulti_backend.ex_riak_leveldb.leveldb.data_root = \$\(platform_data_dir\)\/ex_riak_leveldb/' /etc/riak/riak.conf
  - sudo service riak start
  - sleep 15 # wait for riak start

before_script:
  - sudo riak-admin bucket-type create ex_riak
  - sudo riak-admin bucket-type create ex_riak_maps '{"props":{"datatype":"map"}}'
  - sudo riak-admin bucket-type create ex_riak_leveldb '{"props":{"backend":"ex_riak_leveldb"}}'
  - sudo riak-admin bucket-type activate ex_riak
  - sudo riak-admin bucket-type activate ex_riak_maps
  - sudo riak-admin bucket-type activate ex_riak_leveldb
  - mix local.hex --force
  - mix deps.get --only test
  - mix deps.clean --unused
  - MIX_ENV=test mix compile --warnings-as-errors
  - MIX_ENV=test travis_wait mix dialyzer --plt

script:
  - mix test
  - MIX_ENV=test mix credo --strict
  - MIX_ENV=test mix dialyzer --halt-exit-status
  - if [ "$EX_RIAK_SKIP_MIX_FORMAT" != "yes" ]; then MIX_ENV=test mix format --check-formatted; fi

after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
